### Constants
@host = 172.25.80.1
@port = 8111
@user = admin
@password = admin


### GET project by id
GET http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/projects/id:projectId_1
Content-Type: application/json
Accept: application/json


### GET project by name
GET http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/projects/name:projectId_1
Content-Type: application/json
Accept: application/json