name: Deploy to production

on: workflow_call

# Это лишь примерные степы, как может выглядеть пайплайн
jobs:
  deploy-be:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend to production
        run: echo Происходит деплой бэкенда

  deploy-fe:
    needs: deploy-be
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend to production
        run: echo Происходит деплой фронтенда